import Header from "@/components/header";
import { Card } from "@/components/ui/card";
import { useToast } from "@/hooks/use-toast";
import { api } from "@/utils/api";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Fragment } from "react";

export default function Home() {
  const products = api.product.getAll.useQuery();

  const { toast } = useToast();

  const { refetch: refetchCart } = api.cart.getCart.useQuery();

  const addItem = api.cart.addItem.useMutation({
    onSuccess: () => {
      refetchCart();
      toast({
        title: "Product added to cart",
        description: "The product has been successfully added to your cart.",
      });
    },
  });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="grid min-h-screen grid-cols-4 items-start justify-center gap-3">
        {products.data?.map((product) => (
          <Fragment key={product.id}>
            <Card className="flex flex-col gap-1 text-wrap pb-2">
              <div className="h-[300px] w-[300px] overflow-hidden">
                <Image
                  src={product.images[0] ? product.images[0].imageURL : ""}
                  width={300}
                  height={300}
                  alt={product.name}
                  objectFit="cover"
                  layout="intrinsic"
                />
              </div>
              <div className="space-y-1 text-wrap px-2 text-sm">
                <p className="text-green-700">
                  Rp{product.price.toLocaleString("id-ID")}
                </p>
                <p>{product.name}</p>
                <div className="flex justify-between">
                  <p
                    className="cursor-pointer rounded-md border bg-primary px-2 text-background"
                    onClick={() =>
                      addItem.mutate({ productId: product.id, quantity: 1 })
                    }
                  >
                    +cart
                  </p>
                  <Link href={`/checkout?id=${product.id}`}>
                    <p className="rounded-md border bg-primary px-2 text-background">
                      buy now
                    </p>
                  </Link>
                </div>
              </div>
            </Card>
          </Fragment>
        ))}
      </div>
    </>
  );
}
